local function opcode(ins, addrm, cyc, pc)
    return {
        instruction = ins,
        addr_mode = addrm,
        cycles = cyc,
        add_if_page_crossed = pc or false
    }
end

local opcodes = {
    [0x01] = opcode("ORA", "INDIRECT,X", 6),
    [0x05] = opcode("ORA", "ZERO_PAGE", 3),
    [0x09] = opcode("ORA", "INMEDIATE", 2),
    [0x0d] = opcode("ORA", "ABSOLUTE", 4),
    [0x10] = opcode("BPL", "RELATIVE", 2),
    [0x11] = opcode("ORA", "INDIRECT,Y", 5, true),
    [0x15] = opcode("ORA", "ZERO_PAGE,X", 4),
    [0x18] = opcode("CLC", "IMPLIED", 2),
    [0x1d] = opcode("ORA", "ABSOLUTE,X", 4, true),
    [0x19] = opcode("ORA", "ABSOLUTE,Y", 4, true),
    [0x20] = opcode("JSR", "ABSOLUTE", 6),
    [0x24] = opcode("BIT", "ZERO_PAGE", 3),
    [0x2c] = opcode("BIT", "ABSOLUTE", 4),
    [0x30] = opcode("BMI", "RELATIVE", 2),
    [0x38] = opcode("SEC", "IMPLIED", 2),
    [0x50] = opcode("BVC", "RELATIVE", 2),
    [0x58] = opcode("CLI", "IMPLIED", 2),
    [0x60] = opcode("RTS", "IMPLIED", 6),
    [0x70] = opcode("BVS", "RELATIVE", 2),
    [0x78] = opcode("SEI", "IMPLIED", 2),
    [0x81] = opcode("STA", "INDIRECT,X", 6),
    [0x85] = opcode("STA", "ZERO_PAGE", 3),
    [0x86] = opcode("STX", "ZERO_PAGE", 3),
    [0x88] = opcode("DEY", "IMPLIED", 2),
    [0x8a] = opcode("TXA", "IMPLIED", 2),
    [0x8d] = opcode("STA", "ABSOLUTE", 4),
    [0x8e] = opcode("STX", "ABSOLUTE", 4),
    [0x90] = opcode("BCC", "RELATIVE", 2),
    [0x91] = opcode("STA", "INDIRECT,Y", 6),
    [0x95] = opcode("STA", "ZERO_PAGE,X", 4),
    [0x98] = opcode("TYA", "IMPLIED", 2),
    [0x99] = opcode("STA", "ABSOLUTE,Y", 5),
    [0x9a] = opcode("TXS", "IMPLIED", 2),
    [0x9d] = opcode("STA", "ABSOLUTE,X", 5),
    [0xa0] = opcode("LDY", "INMEDIATE", 2),
    [0xa2] = opcode("LDX", "INMEDIATE", 2),
    [0xa8] = opcode("TAY", "IMPLIED", 2),
    [0xa9] = opcode("LDA", "INMEDIATE", 2),
    [0xaa] = opcode("TAX", "IMPLIED", 2),
    [0xad] = opcode("LDA", "ABSOLUTE", 4),
    [0xb0] = opcode("BCS", "RELATIVE", 2),
    [0xb8] = opcode("CLV", "IMPLIED", 2),
    [0xb9] = opcode("LDA", "ABSOLUTE,Y", 4, true),
    [0xba] = opcode("TSX", "IMPLIED", 2),
    [0xbc] = opcode("LDY", "ABSOLUTE,X", 4, true),
    [0xbd] = opcode("LDA", "ABSOLUTE,X", 4, true),
    [0xbe] = opcode("LDX", "ABSOLUTE,Y", 4, true),
    [0xc0] = opcode("CPY", "INMEDIATE", 2),
    [0xc4] = opcode("CPY", "ZERO_PAGE", 3),
    [0xc8] = opcode("INY", "IMPLIED", 2),
    [0xc9] = opcode("CMP", "INMEDIATE", 2),
    [0xca] = opcode("DEX", "IMPLIED", 2),
    [0xcc] = opcode("CPY", "ABSOLUTE", 4),
    [0xd0] = opcode("BNE", "RELATIVE", 2),
    [0xd8] = opcode("CLD", "IMPLIED", 2),
    [0xe0] = opcode("CPX", "INMEDIATE", 2),
    [0xe4] = opcode("CPX", "ZERO_PAGE", 3),
    [0xe8] = opcode("INX", "IMPLIED", 2),
    [0xec] = opcode("CPX", "ABSOLUTE", 4),
    [0xf0] = opcode("BEQ", "RELATIVE", 2),
    [0xf8] = opcode("SED", "IMPLIED", 2),
}

return opcodes
